# MYSQL
#   gem install mysql2
#
#   Ensure the mysql2 gem is defined in your Gemfile
#   gem 'mysql2'

development:
  adapter: mysql2
  database: en100palabras
  username: root
  password:
  host: 127.0.0.1
