# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caff7a8e8ee41a880836ec82afb7229d4b6e6ba3dee4fce80f1fa84d8fc88fa507171ade6f270c8121a8ebd08a508ab6cc23b1dbf35d1deb4570a0a63d8b7d45

test:
  secret_key_base: c0af8aab323fe99e63c5ef8f17c92567bcd8b884301241450b0019ab5109c3a24463aed8d8d44d2a7d104bf86d9bb786673a4fa2483e39c26eb5986626a3c8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
