# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   city.= City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: city.first)

Region.delete_all
Place.delete_all
City.delete_all

Region.create(name: 'Santiago')
Region.create(name: 'Antofagasta')
Region.create(name: 'Valparaiso')
Region.create(name: 'Concepción')
Region.create(name: 'Iquique')

Place.create(name: 'Primer Lugar')
Place.create(name: 'Segundo Lugar')
Place.create(name: 'Tercer Lugar')
Place.create(name: 'Premio del público')
Place.create(name: 'Premio al talento joven')
Place.create(name: 'Mención honrosa')

City.create(name: 'Algarrobo')
City.create(name: 'Alhué')
City.create(name: 'Alto Biobío')
City.create(name: 'Alto del Carmen')
City.create(name: 'Alto Hospicio')
City.create(name: 'Ancud')
City.create(name: 'Andacollo')
City.create(name: 'Angol')
City.create(name: 'Antártica')
City.create(name: 'Antofagasta')
City.create(name: 'Antuco')
City.create(name: 'Arauco')
City.create(name: 'Arica')
City.create(name: 'Aysén')
City.create(name: 'Buin')
City.create(name: 'Bulnes')
City.create(name: 'Cabildo')
City.create(name: 'Cabo de Hornos')
City.create(name: 'Cabrero')
City.create(name: 'Calama')
City.create(name: 'Calbuco')
City.create(name: 'Caldera')
City.create(name: 'Calera')
City.create(name: 'Calera de Tango')
City.create(name: 'Calle Larga')
City.create(name: 'Camarones')
City.create(name: 'Camiña')
City.create(name: 'Canela')
City.create(name: 'Cañete')
City.create(name: 'Carahue')
City.create(name: 'Cartagena')
City.create(name: 'Casablanca')
City.create(name: 'Castro')
City.create(name: 'Catemu')
City.create(name: 'Cauquenes')
City.create(name: 'Cerrillos')
City.create(name: 'Cerro Navia')
City.create(name: 'Chaitén')
City.create(name: 'Chanco')
City.create(name: 'Chañaral')
City.create(name: 'Chépica')
City.create(name: 'Chiguayante')
City.create(name: 'Chile Chico')
City.create(name: 'Chillán')
City.create(name: 'Chillán Viejo')
City.create(name: 'Chimbarongo')
City.create(name: 'Cholchol')
City.create(name: 'Chonchi')
City.create(name: 'Cisnes')
City.create(name: 'Cobquecura')
City.create(name: 'Cochamó')
City.create(name: 'Cochrane')
City.create(name: 'Codegua')
City.create(name: 'Coelemu')
City.create(name: 'Coihueco')
City.create(name: 'Coinco')
City.create(name: 'Colbún')
City.create(name: 'Colchane')
City.create(name: 'Colina')
City.create(name: 'Collipulli')
City.create(name: 'Coltauco')
City.create(name: 'Combarbalá')
City.create(name: 'Concepción')
City.create(name: 'Conchalí')
City.create(name: 'Concón')
City.create(name: 'Constitución')
City.create(name: 'Contulmo')
City.create(name: 'Copiapó')
City.create(name: 'Coquimbo')
City.create(name: 'Coronel')
City.create(name: 'Corral')
City.create(name: 'Coyhaique')
City.create(name: 'Cunco')
City.create(name: 'Curacautín')
City.create(name: 'Curacaví')
City.create(name: 'Curaco de Vélez')
City.create(name: 'Curanilahue')
City.create(name: 'Curarrehue')
City.create(name: 'Curepto')
City.create(name: 'Curicó')
City.create(name: 'Dalcahue')
City.create(name: 'Diego de Almagro')
City.create(name: 'Doñihue')
City.create(name: 'El Bosque')
City.create(name: 'El Carmen')
City.create(name: 'El Monte')
City.create(name: 'El Quisco')
City.create(name: 'El Tabo')
City.create(name: 'Empedrado')
City.create(name: 'Ercilla')
City.create(name: 'Estación Central')
City.create(name: 'Florida')
City.create(name: 'Freire')
City.create(name: 'Freirina')
City.create(name: 'Fresia')
City.create(name: 'Frutillar')
City.create(name: 'Futaleufú')
City.create(name: 'Futrono')
City.create(name: 'Galvarino')
City.create(name: 'General Lagos')
City.create(name: 'Gorbea')
City.create(name: 'Graneros')
City.create(name: 'Guaitecas')
City.create(name: 'Hijuelas')
City.create(name: 'Hualaihué')
City.create(name: 'Hualañé')
City.create(name: 'Hualpén')
City.create(name: 'Hualqui')
City.create(name: 'Huara')
City.create(name: 'Huasco')
City.create(name: 'Huechuraba')
City.create(name: 'Illapel')
City.create(name: 'Independencia')
City.create(name: 'Iquique')
City.create(name: 'Isla de Maipo')
City.create(name: 'Isla de Pascua')
City.create(name: 'Juan Fernández')
City.create(name: 'La Cisterna')
City.create(name: 'La Cruz')
City.create(name: 'La Estrella')
City.create(name: 'La Florida')
City.create(name: 'La Granja')
City.create(name: 'La Higuera')
City.create(name: 'La Ligua')
City.create(name: 'La Pintana')
City.create(name: 'La Reina')
City.create(name: 'La Serena')
City.create(name: 'La Unión')
City.create(name: 'Lago Ranco')
City.create(name: 'Lago Verde')
City.create(name: 'Laguna Blanca')
City.create(name: 'Laja')
City.create(name: 'Lampa')
City.create(name: 'Lanco')
City.create(name: 'Las Cabras')
City.create(name: 'Las Condes')
City.create(name: 'Lautaro')
City.create(name: 'Lebu')
City.create(name: 'Licantén')
City.create(name: 'Limache')
City.create(name: 'Linares')
City.create(name: 'Litueche')
City.create(name: 'Llaillay')
City.create(name: 'Llanquihue')
City.create(name: 'Lo Barnechea')
City.create(name: 'Lo Espejo')
City.create(name: 'Lo Prado')
City.create(name: 'Lolol')
City.create(name: 'Loncoche')
City.create(name: 'Longaví')
City.create(name: 'Lonquimay')
City.create(name: 'Los Álamos')
City.create(name: 'Los Andes')
City.create(name: 'Los Ángeles')
City.create(name: 'Los Lagos')
City.create(name: 'Los Muermos')
City.create(name: 'Los Sauces')
City.create(name: 'Los Vilos')
City.create(name: 'Lota')
City.create(name: 'Lumaco')
City.create(name: 'Machalí')
City.create(name: 'Macul')
City.create(name: 'Máfil')
City.create(name: 'Maipú')
City.create(name: 'Malloa')
City.create(name: 'Marchihue')
City.create(name: 'María Elena')
City.create(name: 'María Pinto')
City.create(name: 'Mariquina')
City.create(name: 'Maule')
City.create(name: 'Maullín')
City.create(name: 'Mejillones')
City.create(name: 'Melipeuco')
City.create(name: 'Melipilla')
City.create(name: 'Molina')
City.create(name: 'Monte Patria')
City.create(name: 'Mostazal')
City.create(name: 'Mulchén')
City.create(name: 'Nacimiento')
City.create(name: 'Nancagua')
City.create(name: 'Natales')
City.create(name: 'Navidad')
City.create(name: 'Negrete')
City.create(name: 'Ninhue')
City.create(name: 'Nogales')
City.create(name: 'Nueva Imperial')
City.create(name: 'Ñiquén')
City.create(name: 'Ñuñoa')
City.create(name: 'O\'Higgins')
City.create(name: 'Olivar')
City.create(name: 'Ollagüe')
City.create(name: 'Olmué')
City.create(name: 'Osorno')
City.create(name: 'Ovalle')
City.create(name: 'Padre Hurtado')
City.create(name: 'Padre Las Casas')
City.create(name: 'Paiguano')
City.create(name: 'Paillaco')
City.create(name: 'Paine')
City.create(name: 'Palena')
City.create(name: 'Palmilla')
City.create(name: 'Panguipulli')
City.create(name: 'Panquehue')
City.create(name: 'Papudo')
City.create(name: 'Paredones')
City.create(name: 'Parral')
City.create(name: 'Pedro Aguirre Cerda')
City.create(name: 'Pelarco')
City.create(name: 'Pelluhue')
City.create(name: 'Pemuco')
City.create(name: 'Pencahue')
City.create(name: 'Penco')
City.create(name: 'Peñaflor')
City.create(name: 'Peñalolén')
City.create(name: 'Peralillo')
City.create(name: 'Perquenco')
City.create(name: 'Petorca')
City.create(name: 'Peumo')
City.create(name: 'Pica')
City.create(name: 'Pichidegua')
City.create(name: 'Pichilemu')
City.create(name: 'Pinto')
City.create(name: 'Pirque')
City.create(name: 'Pitrufquén')
City.create(name: 'Placilla')
City.create(name: 'Portezuelo')
City.create(name: 'Porvenir')
City.create(name: 'Pozo Almonte')
City.create(name: 'Primavera')
City.create(name: 'Providencia')
City.create(name: 'Puchuncaví')
City.create(name: 'Pucón')
City.create(name: 'Pudahuel')
City.create(name: 'Puente Alto')
City.create(name: 'Puerto Montt')
City.create(name: 'Puerto Octay')
City.create(name: 'Puerto Varas')
City.create(name: 'Pumanque')
City.create(name: 'Punitaqui')
City.create(name: 'Punta Arenas')
City.create(name: 'Puqueldón')
City.create(name: 'Purén')
City.create(name: 'Purranque')
City.create(name: 'Putaendo')
City.create(name: 'Putre')
City.create(name: 'Puyehue')
City.create(name: 'Queilén')
City.create(name: 'Quellón')
City.create(name: 'Quemchi')
City.create(name: 'Quilaco')
City.create(name: 'Quilicura')
City.create(name: 'Quilleco')
City.create(name: 'Quillón')
City.create(name: 'Quillota')
City.create(name: 'Quilpué')
City.create(name: 'Quinchao')
City.create(name: 'Quinta de Tilcoco')
City.create(name: 'Quinta Normal')
City.create(name: 'Quintero')
City.create(name: 'Quirihue')
City.create(name: 'Rancagua')
City.create(name: 'Ránquil')
City.create(name: 'Rauco')
City.create(name: 'Recoleta')
City.create(name: 'Renaico')
City.create(name: 'Renca')
City.create(name: 'Rengo')
City.create(name: 'Requínoa')
City.create(name: 'Retiro')
City.create(name: 'Rinconada')
City.create(name: 'Río Bueno')
City.create(name: 'Río Claro')
City.create(name: 'Río Hurtado')
City.create(name: 'Río Ibáñez')
City.create(name: 'Río Negro')
City.create(name: 'Río Verde')
City.create(name: 'Romeral')
City.create(name: 'Saavedra')
City.create(name: 'Sagrada Familia')
City.create(name: 'Salamanca')
City.create(name: 'San Antonio')
City.create(name: 'San Bernardo')
City.create(name: 'San Carlos')
City.create(name: 'San Clemente')
City.create(name: 'San Esteban')
City.create(name: 'San Fabián')
City.create(name: 'San Felipe')
City.create(name: 'San Fernando')
City.create(name: 'San Gregorio')
City.create(name: 'San Ignacio')
City.create(name: 'San Javier')
City.create(name: 'San Joaquín')
City.create(name: 'San José de Maipo')
City.create(name: 'San Juan de la Costa')
City.create(name: 'San Miguel')
City.create(name: 'San Nicolás')
City.create(name: 'San Pablo')
City.create(name: 'San Pedro')
City.create(name: 'San Pedro de Atacama')
City.create(name: 'San Pedro de La Paz')
City.create(name: 'San Rafael')
City.create(name: 'San Ramón')
City.create(name: 'San Rosendo')
City.create(name: 'San Vicente')
City.create(name: 'Santa Bárbara')
City.create(name: 'Santa Cruz')
City.create(name: 'Santa Juana')
City.create(name: 'Santa María')
City.create(name: 'Santiago')
City.create(name: 'Santo Domingo')
City.create(name: 'Sierra Gorda')
City.create(name: 'Talagante')
City.create(name: 'Talca')
City.create(name: 'Talcahuano')
City.create(name: 'Taltal')
City.create(name: 'Temuco')
City.create(name: 'Teno')
City.create(name: 'Teodoro Schmidt')
City.create(name: 'Tierra Amarilla')
City.create(name: 'Tiltil')
City.create(name: 'Timaukel')
City.create(name: 'Tirúa')
City.create(name: 'Tocopilla')
City.create(name: 'Toltén')
City.create(name: 'Tomé')
City.create(name: 'Torres del Paine')
City.create(name: 'Tortel')
City.create(name: 'Traiguén')
City.create(name: 'Treguaco')
City.create(name: 'Tucapel')
City.create(name: 'Valdivia')
City.create(name: 'Vallenar')
City.create(name: 'Valparaíso')
City.create(name: 'Vichuquén')
City.create(name: 'Victoria')
City.create(name: 'Vicuña')
City.create(name: 'Vilcún')
City.create(name: 'Villa Alegre')
City.create(name: 'Villa Alemana')
City.create(name: 'Villarrica')
City.create(name: 'Viña del Mar')
City.create(name: 'Vitacura')
City.create(name: 'Yerbas Buenas')
City.create(name: 'Yumbel')
City.create(name: 'Yungay')
City.create(name: 'Zapallar')
